### ISSUE TITLE
JavaScript error after building

### ISSUE THREAD

**Issue by Ivi104** [wikimedia-gadgets/twinkle-starter#26] opened 2021-08-30 03:23 UTC
I modified the code and everything works from localhost.
When I build it and move it to Wikipedia (hrwiki), I get the following console error:
`JavaScript parse error (scripts need to be valid ECMAScript 5): Parse error: Missing ; before statement in file 'MediaWiki:Gadget-Twinkle.js' on line 17`
I tried several versions of the code, including building twinkle-starter without changing anything - it still results in this error.
Could someone please help?

**Comment by siddharthvp** [comment] 2021-08-30 04:12
Hi @Ivi104. Could you share a link to your repository? Looking at https://hr.wikipedia.org/wiki/MediaWiki:Gadget-Twinkle.js nothing immediately looks wrong.

**Comment by Ivi104** [comment] 2021-08-30 11:03
Sure @siddharthvp, the repository is at https://github.com/Ivi104/twinkle-hrwiki-template. This is the base template with no changes to the code at all.

**Comment by siddharthvp** [comment] 2021-08-30 11:18
Well, I meant the repo from which [this build](https://hr.wikipedia.org/wiki/MediaWiki:Gadget-Twinkle.js) was generated. 

Taking a 2nd look, it contains `class e{constructor(e)` in the first line which indeed isn't valid ES5. Did you use `npm run build` to build or some other command? A correctly generated build should look more like this: https://test.wikipedia.org/wiki/MediaWiki:Gadget-twinkle-bundle.js. The ES6 class syntax should have been transpiled away.

**Comment by Ivi104** [comment] 2021-08-30 12:22
@siddharthvp that is the repo from which that build was generated. Let's first fix the problems in the base version before moving on. The commands I used were `npm install` and `grunt build`, as provided in the readme. The command `npm run build` also had no effect, the resulting code has no difference than the previous one, and it still contains the offending code `class e{constructor(e)`.

**Comment by siddharthvp** [comment] 2021-08-30 15:00
@Ivi104 Indeed. This is embarrassing - the base had been properly tested earlier but a later change in the orange-i18n library is breaking the build. Looking into it ...

**Comment by siddharthvp** [comment] 2021-08-30 16:31
Turns out the issue wasn't caused by a change in orange-i18n. Anyway, [this fix](https://github.com/wikimedia-gadgets/twinkle-starter/commit/8c232ae104455d87c58293b1ed4cb51c8e827ffd) resolves the issue - copy over the package.json and webpack.config.json changes (the package-lock.json changes will be applied automatically when npm install is run). 

It used to work earlier without this, but not sure what changed since then.

Let me know if there's still any issue.

**Comment by Ivi104** [comment] 2021-08-30 17:23
@siddharthvp  This worked like a charm, thank you for taking the time to help!

The console now shows a different syntax error:
`SyntaxError: Invalid regular expression: /(?:([A-Za-zªµºÀ-ÖØ-öø-ʸʻ-ˁːˑˠ-ˤˮͰ-ͳͶͷͺ-ͽͿΆΈ-ΊΌΎ-ΡΣ-ϵϷ-҂Ҋ-ԯԱ-Ֆՙ-՟ա-և։ः-हऻऽ-ीॉ-ौॎ-ॐक़-ॡ।-ঀংঃঅ-ঌএঐও-নপ-রলশ-হঽ-ীেৈোৌৎৗড়ঢ়য়-ৡ০-ৱ৴-৺ਃਅ-ਊਏਐਓ-ਨਪ-ਰਲਲ਼ਵਸ਼ਸਹਾ-ੀਖ਼-ੜਫ਼੦-੯ੲ-ੴઃઅ-ઍએ-ઑઓ-નપ-રલળવ-હઽ-ીૉોૌૐૠૡ૦-૰ૹଂଃଅ-ଌଏଐଓ-ନପ-ରଲଳଵ-ହଽାୀେୈୋୌୗଡ଼ଢ଼ୟ-ୡ୦-୷ஃஅ-ஊஎ-ஐஒ-கஙசஜஞடணதந-பம-ஹாிுூெ-ைொ-ௌௐௗ௦-௲ఁ-ఃఅ-ఌఎ-ఐఒ-నప-హఽు-ౄౘ-ౚౠౡ౦-౯౿ಂಃಅ-ಌಎ-ಐಒ-ನಪ-ಳವ-ಹಽ-ೄೆ-ೈೊೋೕೖೞೠೡ೦-೯ೱೲംഃഅ-ഌഎ-ഐഒ-ഺഽ-ീെ-ൈൊ-ൌൎൗൟ-ൡ൦-൵൹-ൿංඃඅ-ඖක-නඳ-රලව-ෆා-ෑෘ-ෟ෦-෯ෲ-෴ก-ะาำเ-ๆ๏-๛ກຂຄງຈຊຍດ-ທນ-ຟມ-ຣລວສຫອ-ະາຳຽເ-ໄໆ໐-໙ໜ-ໟༀ-༗༚-༴༶༸༾-ཇཉ-ཬཿ྅ྈ-ྌ྾-࿅࿇-࿌࿎-࿚က-ာေးျြဿ-ၗၚ-ၝၡ-ၰၵ-ႁႃႄႇ-ႌႎ-ႜ႞-ჅჇჍა-ቈቊ-ቍቐ-ቖቘቚ-ቝበ-ኈኊ-ኍነ-ኰኲ-ኵኸ-ኾዀዂ-ዅወ-ዖዘ-ጐጒ-ጕጘ-ፚ፠-፼ᎀ-ᎏᎠ-Ᏽᏸ-ᏽᐁ-ᙿᚁ-ᚚᚠ-ᛸᜀ-ᜌᜎ-ᜑᜠ-ᜱ᜵᜶ᝀ-ᝑᝠ-ᝬᝮ-ᝰក-ឳាើ-ៅះៈ។-៚ៜ០-៩᠐-᠙ᠠ-ᡷᢀ-ᢨᢪᢰ-ᣵᤀ-ᤞᤣ-ᤦᤩ-ᤫᤰᤱᤳ-ᤸ᥆-ᥭᥰ-ᥴᦀ-ᦫᦰ-ᧉ᧐-᧚ᨀ-ᨖᨙᨚ᨞-ᩕᩗᩡᩣᩤᩭ-ᩲ᪀-᪉᪐-᪙᪠-᪭ᬄ-ᬳᬵᬻᬽ-ᭁᭃ-ᭋ᭐-᭪᭴-᭼ᮂ-ᮡᮦᮧ᮪ᮮ-ᯥᯧᯪ-ᯬᯮ᯲᯳᯼-ᰫᰴᰵ᰻-᱉ᱍ-᱿᳀-᳇᳓᳡ᳩ-ᳬᳮ-ᳳᳵᳶᴀ-ᶿḀ-ἕἘ-Ἕἠ-ὅὈ-Ὅὐ-ὗὙὛὝὟ-ώᾀ-ᾴᾶ-ᾼιῂ-ῄῆ-ῌῐ-ΐῖ-Ίῠ-Ῥῲ-ῴῶ-ῼ‎ⁱⁿₐ-ₜℂℇℊ-ℓℕℙ-ℝℤΩℨK-ℭℯ-ℹℼ-ℿⅅ-ⅉⅎ⅏Ⅰ-ↈ⌶-⍺⎕⒜-ⓩ⚬⠀-⣿Ⰰ-Ⱞⰰ-ⱞⱠ-ⳤⳫ-ⳮⳲⳳⴀ-ⴥⴧⴭⴰ-ⵧⵯ⵰ⶀ-ⶖⶠ-ⶦⶨ-ⶮⶰ-ⶶⶸ-ⶾⷀ-ⷆⷈ-ⷎⷐ-ⷖⷘ-ⷞ々-〇〡-〩〮〯〱-〵〸-〼ぁ-ゖゝ-ゟァ-ヺー-ヿㄅ-ㄭㄱ-ㆎ㆐-ㆺㇰ-㈜㈠-㉏㉠-㉻㉿-㊰㋀-㋋㋐-㋾㌀-㍶㍻-㏝㏠-㏾㐀-䶵一-鿕ꀀ-ꒌꓐ-ꘌꘐ-ꘫꙀ-ꙮꚀ-ꚝꚠ-ꛯ꛲-꛷Ꜣ-ꞇ꞉-ꞭꞰ-ꞷꟷ-ꠁꠃ-ꠅꠇ-ꠊꠌ-ꠤꠧ꠰-꠷ꡀ-ꡳꢀ-ꣃ꣎-꣙ꣲ-ꣽ꤀-ꤥ꤮-ꥆꥒ꥓꥟-ꥼꦃ-ꦲꦴꦵꦺꦻꦽ-꧍ꧏ-꧙꧞-ꧤꧦ-ꧾꨀ-ꨨꨯꨰꨳꨴꩀ-ꩂꩄ-ꩋꩍ꩐-꩙꩜-ꩻꩽ-ꪯꪱꪵꪶꪹ-ꪽꫀꫂꫛ-ꫫꫮ-ꫵꬁ-ꬆꬉ-ꬎꬑ-ꬖꬠ-ꬦꬨ-ꬮꬰ-ꭥꭰ-ꯤꯦꯧꯩ-꯬꯰-꯹가-힣ힰ-ퟆퟋ-ퟻ-舘並-龎ﬀ-ﬆﬓ-ﬗＡ-Ｚａ-ｚｦ-ﾾￂ-ￇￊ-ￏￒ-ￗￚ-ￜ]|�[�-�]|�[�-�]|�[�-�]|𐀼|𐀽|�[�-�]|�[�-�]|�[�-�]|𐄀|𐄂|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𐕯|�[�-�]|�[�-�]|�[�-�]|𑀀|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𑂷|𑂸|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𑄬|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𑇍|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𑈲|𑈳|𑈵|�[�-�]|�[�-�]|𑊈|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𑌂|𑌃|�[�-�]|𑌏|𑌐|�[�-�]|�[�-�]|𑌲|𑌳|�[�-�]|�[�-�]|�[�-�]|𑍇|𑍈|�[�-�]|𑍐|𑍗|�[�-�]|�[�-�]|𑒹|�[�-�]|𑓁|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𑖾|�[�-�]|�[�-�]|𑘻|𑘼|𑘾|�[�-�]|�[�-�]|�[�-�]|𑚬|𑚮|𑚯|𑚶|�[�-�]|�[�-�]|𑜠|𑜡|𑜦|�[�-�]|�[�-�]|𑣿|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𖩮|𖩯|�[�-�]|𖫵|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𛀀|𛀁|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𛲜|𛲟|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𝆃|𝆄|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𝒞|𝒟|𝒢|𝒥|𝒦|�[�-�]|�[�-�]|𝒻|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|𝕆|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|🉐|🉑|[�-�][�-�]|�[�-�]|�[�-�]|[�-�][�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|[�-�][�-�]|�[�-�]|�[�-�]|[�-�][�-�]|�[�-�]|[�-�][�-�]|�[�-�])|([֐־׀׃׆׈-׿߀-ߪߴߵߺ-ࠕࠚࠤࠨ࠮-ࡘ࡜-࢟‏יִײַ-ﬨשׁ-ﭏ؈؋؍؛-ي٭-ٯٱ-ەۥۦۮۯۺ-ܐܒ-ܯ݋-ޥޱ-޿ࢠ-࣢ﭐ-ﴽ﵀-﷏ﷰ-﷼﷾﷿ﹰ-﻾]|�[�-�]|�[�-�]|𐨄|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]|�[�-�]))/: Range out of order in character class`

Do I open a new issue or ? :)

**Comment by Ivi104** [comment] 2021-08-30 17:40
I fixed it, see https://hr.wikipedia.org/w/index.php?diff=6047405

**Comment by Ivi104** [comment] 2021-08-31 00:35
Another question, I adapted some code from wikimedia-gadgets/twinkle-enwiki (e.g. CSD and Unlink), but as far as I can see, preference arrays for these modules (for use in /Preferences subpage) are not in wikimedia-gadgets/twinkle-enwiki repo nor in wikimedia-gadgets/twinkle-core. Please advise on the quickest way to copy them over to local wiki (preferably without writing everything from scratch).

**Comment by siddharthvp** [comment] 2021-09-02 19:46
I haven't looked at these things lately so not sure. Twinkle-enwiki wasn't fully developed (mainly because of political reasons). If there is anything that you want to add in twinkle-core, any contribution would be welcome.

**Comment by siddharthvp** [comment] 2021-11-20 15:04
The invalid regex issue has been resolved in 28c846bac

**Closed by siddharthvp** 2021-11-20 15:04 UTC
